# syntax=docker/dockerfile:1

FROM node:14.15.4-alpine3.12

EXPOSE 8080

USER root

COPY . /server

WORKDIR /server

RUN yarn install

RUN yarn add cors express mysql express-session bcryptjs passport passport-local passport-jwt jsonwebtoken prisma @prisma/client dotenv nodemon

CMD ["nodemon", "index.js"]
