# syntax=docker/dockerfile:1

FROM node:14.15.4-alpine3.12

EXPOSE 8080

USER root

COPY . /server

WORKDIR /server

RUN yarn install 

RUN yarn global add nodemon

RUN yarn add cors express mysql

CMD ["nodemon", "index.js"]
