# syntax=docker/dockerfile:1

ARG VERSION="stable"
ARG ANDROID_SDK_TOOLS_VERSION=8512546
ARG ANDROID_HOME="/android"

FROM ubuntu:18.04 as build
FROM cirrusci/flutter:2.0.5

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    wget \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /android/cmdline-tools && \
    cd /android/cmdline-tools && \
    wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS_VERSION}_latest.zip && \
    unzip commandlinetools-linux-${ANDROID_SDK_TOOLS_VERSION}_latest.zip && \
    rm commandlinetools-linux-${ANDROID_SDK_TOOLS_VERSION}_latest.zip && \
    mv cmdline-tools latest

COPY .. /home
WORKDIR /home

USER root

ARG ANDROID_PLATFORM_VERSION
ARG ANDROID_SDK_TOOLS_VERSION
ARG ANDROID_HOME

ENV ANDROID_HOME=$ANDROID_HOME \
    ANDROID_SDK_ROOT=$ANDROID_HOME \
    ANDROID_TOOLS_ROOT=$ANDROID_HOME \
    PATH="${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools"

